Draft: Topic 112
DamienHarper/auditor-bundle pull request #328
Opened 2022-10-29 14:07 UTC by dmitryuk

Fixed #112 
Linked with https://github.com/DamienHarper/auditor/pull/118/files

2022-10-29 20:57 UTC, DamienHarper requested changes
Looks good to me, all you have to do is to fix CS

2022-10-30 02:34 UTC, dmitryuk commented
I need a new tag of auditor package to make it works
@DamienHarper, can you make a release?

2022-10-30 21:37 UTC, DamienHarper commented
@dmitryuk here you go: [2.1.0](https://github.com/DamienHarper/auditor/releases/tag/2.1.0)

2022-10-31 06:38 UTC, dmitryuk commented on .php-cs-fixer.php
> +        'get_class_to_class_keyword' => false,
Don't replace `get_class($entity)` to `$entity::class`

2022-10-31 06:41 UTC, dmitryuk commented
@DamienHarper please make a new review, because some other files changed from last one.
Also see `https://github.com/DamienHarper/auditor-docs/pull/11`

2022-10-31 07:45 UTC, DamienHarper approved these changes

2022-10-31 07:45 UTC, merged